# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('nombre', models.CharField(blank=True, max_length=60)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('tipo', models.PositiveSmallIntegerField(default=0)),
                ('genero_codigo', models.BooleanField(default=False)),
                ('codigo_gen', models.IntegerField(blank=True, null=True)),
                ('fecha_gen', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cia',
            fields=[
                ('cia_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=250, unique=True)),
                ('rif', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'db_table': 'cia',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='CiaConsecutivo',
            fields=[
                ('ciaconsecutivo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.PositiveSmallIntegerField(default=0)),
                ('numero', models.IntegerField(default=0)),
                ('cia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciaconsecutivos', to='ia.Cia')),
            ],
            options={
                'db_table': 'cia_consecutivo',
                'ordering': ['cia', 'tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciudad_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'ciudad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('direccion_completa', models.TextField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='c_direcciones', to='ia.Ciudad')),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='DocRep',
            fields=[
                ('docrep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.PositiveSmallIntegerField(choices=[(0, 'N/A'), (1, 'Factura'), (2, 'Nota de Débito'), (3, 'Nota de Crédito'), (4, 'Pedido'), (5, 'Cotización'), (6, 'Solicitud de Devolución'), (7, 'Solicitud de Nota de Crédito'), (8, 'Solicitud de Nota de Débito'), (9, 'Devolución de Mercancía'), (10, 'Orden TOT'), (11, 'NO USADA'), (12, 'Orden de Compra'), (13, 'Solicitud de Cotización'), (14, 'Nota de Entrega'), (15, 'Recepción'), (16, 'Cierre de Inventario'), (17, 'Nota de Entrada al Inventario'), (18, 'Nota de Salida al Inventario'), (19, 'Transferencia'), (20, 'Devolución de Transferencia'), (21, 'Solicitud de Transferencia'), (22, 'Solicitud de Devolución de Transferencia'), (23, 'Cotización de O/S'), (24, 'Orden de Servicio'), (25, 'Reclamo de Garantía'), (26, 'Prefactura'), (27, 'Anticipo'), (28, 'Cheque Devuelto'), (29, 'Giro'), (30, 'Nota de Débito por Mora'), (31, 'Reclamo de Devolución'), (32, 'Cheque')], default=0)),
                ('numero', models.CharField(max_length=35)),
                ('credito', models.BooleanField(default=False)),
                ('dias_credito', models.PositiveSmallIntegerField(default=0)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='c_docreps', to='ia.Cia')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dir_docreps', to='ia.Direccion')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orig_docreps', to='ia.DocRep')),
            ],
            options={
                'db_table': 'doc_rep',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='DocRepDet',
            fields=[
                ('docrepdet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('costo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('docrep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='det_docrepdets', to='ia.DocRep')),
            ],
            options={
                'db_table': 'doc_rep_det',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'estado',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150, null=True)),
                ('cedula_rif', models.CharField(max_length=35, unique=True)),
                ('juridica', models.BooleanField()),
                ('activo', models.BooleanField()),
                ('bloqueado', models.BooleanField()),
                ('ultima_operacion', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='ia.Cia')),
            ],
            options={
                'db_table': 'persona',
                'ordering': ['cedula_rif'],
            },
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_mercantil', models.CharField(max_length=60)),
                ('nro_registro', models.CharField(max_length=10)),
                ('tomo', models.CharField(max_length=6)),
                ('fecha_registro', models.DateTimeField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ia.Persona')),
            ],
            options={
                'db_table': 'persona_juridica',
            },
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True)),
                ('rif', models.CharField(blank=True, max_length=35, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('sexo', models.PositiveSmallIntegerField(default=0)),
                ('estado_civil', models.PositiveSmallIntegerField(default=0)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ia.Persona')),
            ],
            options={
                'db_table': 'persona_natural',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=35)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('costo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('existencia', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='ia.Cia')),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SesionTrabajo',
            fields=[
                ('sesion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mitoken', models.CharField(max_length=512, unique=True)),
                ('parametros', models.TextField(blank=True, null=True)),
                ('cia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='c_sesiontrabajos', to='ia.Cia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='u_sesiontrabajos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sesion_trabajo',
            },
        ),
        migrations.CreateModel(
            name='UserCia',
            fields=[
                ('user_cia_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.PositiveSmallIntegerField(default=0)),
                ('cia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cia_usercias', to='ia.Cia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='u_usercias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_cia',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('user_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('sesion', models.CharField(max_length=512)),
                ('cia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cia_userlogs', to='ia.Cia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='u_userlogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_log',
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados', to='ia.Pais'),
        ),
        migrations.AddField(
            model_name='docrepdet',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prod_docrepdets', to='ia.Producto'),
        ),
        migrations.AddField(
            model_name='docrep',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p_docreps', to='ia.Persona'),
        ),
        migrations.AddField(
            model_name='docrep',
            name='uanula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uanu_docreps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docrep',
            name='uaprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uapro_docreps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docrep',
            name='ucrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ucrea_docreps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docrep',
            name='ufactura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ufact_docreps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direccion',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='e_direcciones', to='ia.Estado'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p_direcciones', to='ia.Pais'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p_direcciones', to='ia.Persona'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='ia.Estado'),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set([('cia', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set([('cia', 'cedula_rif')]),
        ),
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together=set([('pais', 'nombre')]),
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together=set([('estado', 'nombre')]),
        ),
        migrations.AlterUniqueTogether(
            name='ciaconsecutivo',
            unique_together=set([('cia', 'tipo_documento')]),
        ),
    ]
