# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cias', to='ia.Cia'),
        ),
    ]
