# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_usuario_cia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('perfil_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='PerfilDet',
            fields=[
                ('perfildet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='det_perfiles', to='ia.Perfil')),
            ],
            options={
                'db_table': 'perfildet',
            },
        ),
        migrations.CreateModel(
            name='UserPerfil',
            fields=[
                ('userperfil_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='ia.Perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userperfil',
            },
        ),
        migrations.CreateModel(
            name='Ventana',
            fields=[
                ('ventana_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ventana',
            },
        ),
        migrations.AddField(
            model_name='perfildet',
            name='ventana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='det_ventanas', to='ia.Ventana'),
        ),
        migrations.AlterUniqueTogether(
            name='userperfil',
            unique_together=set([('usuario', 'perfil')]),
        ),
        migrations.AlterUniqueTogether(
            name='perfildet',
            unique_together=set([('ventana', 'perfil', 'evento')]),
        ),
    ]
