# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0004_auto_20170509_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tz',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
