# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0006_estado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
